FORMAT: 1A

#VUTTR

This is a simple api with a simple jwt authentication that allows to manage tools with its name, url, description and tags.

## Register collection [/register]

### Register [POST]

You may create your user to the application by the following parameters:

+ name (string) -  Name
+ email (string) - Your email
+ password (string) - Your password

+ Request (application/json)

        {
            "name": "Jon Doe",
            "email": "jondoe@example.com",
            "password": "123456"
        }

+ Response 200 (application/json)

        {
          "user": {
            "_id": "5cdca401e914cf33ab489b5f",
            "name": "Jon Doe",
            "email": "jondoe@example.com",
            "createdAt": "2019-05-15T23:42:57.489Z",
            "__v": 0
          }
        }

## Login Collection [/]

### login [POST]

You may create your user to the application by the following parameters:

+ email  (string) - Your email
+ password (string) - Your password

+ Request (application/json)

        {
            "email": "jondoe@example.com",
            "password": "123456"
        }

+ Response 200 (application/json)

        {
          "user": {
            "_id": "5cdca401e914cf33ab489b5f",
            "name": "Jon Doe",
            "email": "jondoe@example.com",
            "createdAt": "2019-05-15T23:42:57.489Z",
            "__v": 0
          },
          "token": "(a bearer token)"
        }


## Tools collection [/tools]

### List all tools [GET]

+ Response 200 (application/json)

        [
        {
            _id: "5cdd610800f01547ba9e5e3a"
            title: "Notion",
            link: "https://notion.so",
            description: "All in one tool to organize teams and ideas. Write, plan, collaborate, and get organized. ",
            tags: [
                "organization",
                "planning",
                "collaboration",
                "writing",
                "calendar"
            ]
        },
        {
            id: "5cdd610800f01547ba9e5e3b",
            title: "json-server",
            link: "https://github.com/typicode/json-server",
            description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
            tags: [
                "api",
                "json",
                "schema",
                "node",
                "github",
                "rest"
            ]
        },
        {
            id: "5cdd610800f01547ba9e5e3c",
            title: "fastify",
            link: "https://www.fastify.io/",
            description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
            tags: [
                "web",
                "framework",
                "node",
                "http2",
                "https",
                "localhost"
            ]
        }
        ]
### Describe a new tool [POST]

You may create describe your own tool using this action. It takes a JSON object containing the following:

+ title (string) -  Title
+ description (string) - Description of the tool
+ link (string) - URI of the tool
+ tags ([string]) - tags that may represent the tool

+ Request (application/json)

        {
            "title": "hotel",
            "link": "https://github.com/typicode/hotel",
            "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box.",
            "tags":["node", "organizing", "webapps", "domain", "developer", "https", "proxy"]
        }

+ Response 200 (application/json)

        {
        "tags": [
            "node",
            "organizing",
            "webapps",
            "domain",
            "developer",
            "https",
            "proxy"
        ],
        "_id": "5cdd9e03d622e84c40c5e25f",
        "title": "hotel",
        "link": "https://github.com/typicode/hotel",
        "description": "Local app manager. Start apps within your browser, developer tool with local .localhost domain and https out of the box."
        }





### Tag [/tools?tag={tag}]

+ Parameters
    + tag: node (required, string) - Tag of a tool as a string
    
### Search using tag name [GET]

+ Response 200 (application/json)

        [
        {
            id: "5cdd600bef45484791384acd",
            title: "json-server",
            link: "https://github.com/typicode/json-server",
            description: "Fake REST API based on a json schema. Useful for mocking and creating APIs for front-end devs to consume in coding challenges.",
            tags: [
                "api",
                "json",
                "schema",
                "node",
                "github",
                "rest"
            ]
        },
        {
            id: "5cdd610800f01547ba9e5e3a",
            title: "fastify",
            link: "https://www.fastify.io/",
            description: "Extremely fast and simple, low-overhead web framework for NodeJS. Supports HTTP2.",
            tags: [
                "web",
                "framework",
                "node",
                "http2",
                "https",
                "localhost"
            ]
        }
        ]
### Delete [/tools/{tool_id}]

+ Parameters
    + tool_id: 5cdd5fdaef45484791384acc (required, string) - id of a tool
    
### Delete [POST]

+ Response 200